# Generated by Django 3.2.13 on 2023-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiquinhoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('números', models.TextField()),
                ('tipo', models.TextField()),
                ('essa_temporada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TiquinhoTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('time', models.TextField()),
                ('gols', models.TextField()),
                ('clube_atual', models.BooleanField()),
            ],
        ),
    ]
